### ISSUE TITLE
New entities class diagram design

### ISSUE THREAD

**Issue by tildehacker** [g2foss-org/g2foss-club-manager#18]
This is an issue to discuss the new entities class diagram proposed by @chicoslatinos 

The original link is: https://github.com/orgs/g2foss-org/teams/club-manager/discussions/4

**Comment by tildehacker** [comment]
- Naming conventions: please follow https://symfony.com/doc/current/contributing/code/standards.html (camelCase for methods and variables and CamelCase for classes).

- Names I suggest for entities: Person->User, Type->Role, Workshops->Workshop, Taches->Task and event_standard->Event.

- The relationship between Person(->User) and Type(->Role) is an aggregation (a Role is made up of one or more Users).
- The relationship between Person(->User) and Taches(->Task) is an aggregation (a Task is made up of one or more Users).
- The relationship between Person(->User) and Workshops(->Workshop) is an aggregation (a Workshop is made up of one or more Users).
- Another relationship should be made between Person(->User) and Workshops(->Workshop) for the formateur(->trainer).
- The relationship between Person(->User) and Cell is an aggregation (a Cell is made up of one or more Users). We may add an association class for the type of responsibility of the User in this Cell.
- The relationship between Cell and Taches(->Task) is a composition (a Cell is made up of one ore more Tasks and if a Cell is destroyed, Tasks are destroyed too).
- The relationship between event_standard(->Event) and Cell is a composition (an Event is made up of one or more Cells, and if an Event is destroyed, Cells are destroyed too).
- We need more information about different sections (atelier de développement, atelier de sécurité,...) so we need an entity for that (class Atelier https://github.com/g2foss-org/g2foss-club-manager/issues/5#issuecomment-459937909).

- persons attribute in Workshops(->Workshop) and Cell is redundant (the association is enough).
- responsible, persons, taches and event attributes are redundant in Cell (the associations are enough).
- formateur(->trainer) attribute is redundant in Workshops(->Workshop), the association is enough.

We are tracking UML diagrams changes in this folder https://github.com/g2foss-org/g2foss-club-manager/tree/develop/diagrams. Please use https://www.visual-paradigm.com/download/community.jsp to make changes to this file, add files a new branch (same folder) and open a new pull request.

**Comment by chicoslatinos** [comment]
Thank you for your remarks @tildehacker but just to let you know that i can't specify in Symfony the type of associations it's up to us how to see or use it so it will only change in the design but not in the entities or tables.

An other thing for the last point it was a mistake I'm sorry for that it is just the association.

@g2foss-org/club-manager please give me your remarks here so i know it's done well or not we can't always depend on the meeting to fix things. Thank you in advance

**Comment by BOUSSAIDIKHALED** [comment]
![image](https://user-images.githubusercontent.com/47223663/52824827-87afb380-30ba-11e9-98ce-c4d5d27590f2.png)

**Comment by tildehacker** [comment]
@BOUSSAIDIKHALED Could you please share the source file? 

_Envoyé depuis mon Galaxy A3(2016) en utilisant [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by tildehacker** [comment]
@BOUSSAIDIKHALED Could you please share the source file?

**Comment by tildehacker** [comment]
Implemented in pull request #19. Issue closed.
