### ISSUE TITLE
Can't migrate the project

### ISSUE THREAD

**Issue by chicoslatinos** [g2foss-org/g2foss-club-manager#25]
In SchemaException.php line 108:

  The table with name 'g2foss.workshop_user' already exists.

make:migration [--db DB] [--em [EM]] [--shard SHARD] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-e|--env ENV] [--no-debug] [--] <command>

**Comment by tildehacker** [comment]
Fixed in: https://github.com/g2foss-org/g2foss-club-manager/commit/fe5e8fb1744dc5c5626fca482d8f4f090352d860 and https://github.com/g2foss-org/g2foss-club-manager/commit/b036efee1487db63f2450afd7cc15ad086e67cc5.

Please follow these steps to check if it's fixed for you:
```bash
git clone git@github.com:g2foss-org/g2foss-club-manager.git migration-test
cd migration-test
git checkout fedi
composer install
# Edit .env file to add database URL (new empty database name)
php bin/console doctrine:database:create
php bin/console make:migration
php bin/console doctrine:migrations:migrate
```
