### ISSUE TITLE
Model entities UML diagram using Visual Paradigm.

### ISSUE THREAD

**Issue by tildehacker** [g2foss-org/g2foss-club-manager#5]
Use https://www.visual-paradigm.com to model entities UML diagrams and commit to new branch.

**Comment by Klaimohelmi** [comment]
![membre](https://user-images.githubusercontent.com/47222865/52160438-a757dc80-26b5-11e9-9f4c-57a69cc77df1.jpg)

**Comment by Klaimohelmi** [comment]
[Etudiant.zip](https://github.com/g2foss-org/g2foss-club-manager/files/2824576/Etudiant.zip)

**Comment by tildehacker** [comment]
> [Etudiant.zip](https://github.com/g2foss-org/g2foss-club-manager/files/2824576/Etudiant.zip)

Le fichier .vpp est binaire et ne permet pas de générer une diff avec git. On choisira un autre outil avant d'ajouter le diagramme au repo.
