### ISSUE TITLE
Prototype signup page.

### ISSUE THREAD

**Issue by tildehacker** [g2foss-org/g2foss-club-manager#8]
Use https://getbootstrap.com/docs/4.2/components to prototype a signup page.

**Comment by tildehacker** [comment]
@MehdiGhannem please write you changes in a new branch and submit a pull request

**Comment by chicoslatinos** [comment]
@MehdiGhannem I need the login page code so i can work with it

**Comment by tildehacker** [comment]
> @MehdiGhannem I need the login page code so i can work with it

@MehdiGhannem submitted a pull request #21 for this but it's not yet merged into develop (I requested some changes).
